language: node_js
node_js:	
  - "8"

services:
  - docker

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

script:
  - npm run test -- --code-coverage --no-progress --browsers=ChromeHeadlessCI

after_success:
  - npm run codecov

before_deploy:
  - docker build -t upec-entrepreneurs .

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    all_branches: true